# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f88f7ff902c022142cefd9664f210af2b29710fb15e14a11c225f6b7467695f75caf52f0de63979d29e23ebbcbc5e44628440072379028be4a05a731487dee

test:
  secret_key_base: e77883a98cdeb3d65af3df6c6b1fa3e17e84cbf7d00610f07939b5be7da1c49b8941ae822e7ed0d5ddd3f9ac6224a5c5f74ed681f549256ec8b68ea55ddeba7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
